name: generador_de_json
description: Herramienta para generar archivos JSON a partir de modelos de datos.
version: 1.1.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.2 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
